<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Factories\HasFactory;
use Illuminate\Database\Eloquent\Model;

class Report extends Model
{
    use HasFactory;

    // Table name (optional, Laravel auto handles it)
    protected $table = 'reports';

    // Mass assignable fields
    protected $fillable = [
        'title',
        'total_teams',
        'total_students',
        'total_supervisors',
        'total_proposals',
        'approved_proposals',
        'pending_proposals',
        'rejected_proposals',
        'generated_by'
    ];

    // Relationship: report generated by admin
    public function admin()
    {
        return $this->belongsTo(User::class, 'generated_by');
    }
}